### ISSUE TITLE
Ublock doesnt like Adapt very much

### ISSUE THREAD

**Issue by vvirtues** [AdaptChat/webclient#3]
![image](https://github.com/AdaptChat/webclient/assets/81705406/c7fdd3dd-1318-4d2b-b429-05b4f32eef67)
![image](https://github.com/AdaptChat/webclient/assets/81705406/05eaf2bf-ac31-43db-a8a9-d6d157274de9)
works fine when its off

**Comment by 0xQueen** [comment]
Doesn't happen to me.

**Comment by vvirtues** [comment]
yea i cant reproduce anymore
